CREATE TABLE IF NOT EXISTS users (
	id 			CHAR(36) NOT NULL,
	created 	DATETIME NOT NULL,
	updated 	DATETIME NOT NULL,
	name 		VARCHAR(255) NOT NULL,
	email 		VARCHAR(255) NOT NULL UNIQUE,
	password 	VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
);
